# Site settings
title: Brandon Hernandez
author: Brandon Hernandez
  name: Brandon Hernandez
  email: bthernandez0915@gmail.com
description: "My personal webpage."

# Build settings
remote_theme: jekyll/minima
